### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by lemmonation** [facebookresearch/Mask-Predict#2]
could you provide the details about the environment requirements to run this code? Which pytorch version do you use?

**Comment by yinhanliu** [comment]
https://hub.docker.com/layers/pytorch/pytorch/nightly-runtime-cuda10.0-cudnn7/images/sha256-ee8db081f5f6de86637fc2ff28ac860afc249c23c5dc38b8f67ff0108e5d3095
