### ISSUE TITLE
Will you release the dataset of wmt17-enzh ?

### ISSUE THREAD

**Issue by JackHorse** [facebookresearch/Mask-Predict#5]
Hi，

I want reproduce your result of wmt17-enzh, but your released model doesn't contain the bpe codes.
Will you release wmt17-enzh dataset ? 

tks

**Comment by yinhanliu** [comment]
we released a dictionary. you can bpe based on our dictionary.

**Comment by tdomhan** [comment]
any reason not to release the BPE models? In order to reproduce BPE encoding one needs to reproduce the same order of merge operations to resolve ambiguities (ab + c vs a + bc). So just using the dictionary directly does not work.
